POST {{host}}/information/text-content
content-type: application/json

{
    "content": "ในปี 2568 มีวันหยุดธนาคารรวมทั้งสิ้น 19 วัน โดยเริ่มตั้งแต่วันขึ้นปีใหม่ในวันที่ 1 มกราคม, วันมาฆบูชาในวันที่ 12 กุมภาพันธ์, วันชดเชยวันจักรีในวันที่ 7 เมษายน, และวันสงกรานต์ในวันที่ 14–15 เมษายน ต่อด้วยวันแรงงานแห่งชาติในวันที่ 1 พฤษภาคม, วันชดเชยวันฉัตรมงคลในวันที่ 5 พฤษภาคม, วันชดเชยวันวิสาขบูชาในวันที่ 12 พฤษภาคม และวันหยุดพิเศษในวันที่ 2 มิถุนายน ก่อนถึงวันเฉลิมพระชนมพรรษาสมเด็จพระนางเจ้าฯ พระบรมราชินีในวันที่ 3 มิถุนายน ในช่วงครึ่งปีหลังยังมีวันอาสาฬหบูชาในวันที่ 10 กรกฎาคม, วันเฉลิมพระชนมพรรษาพระบาทสมเด็จพระเจ้าอยู่หัวในวันที่ 28 กรกฎาคม, วันหยุดพิเศษในวันที่ 11 สิงหาคม และวันแม่แห่งชาติในวันที่ 12 สิงหาคม จากนั้นคือวันคล้ายวันสวรรคต รัชกาลที่ 9 ในวันที่ 13 ตุลาคม, วันปิยมหาราชในวันที่ 23 ตุลาคม, วันพ่อแห่งชาติและวันชาติในวันที่ 5 ธันวาคม, วันรัฐธรรมนูญในวันที่ 10 ธันวาคม และสิ้นสุดปีด้วยวันสิ้นปีในวันที่ 31 ธันวาคม."
}

###

POST {{host}}/information/path-file
content-type: application/json

{
    "pathFile": "src/common/files/schedule.json"
}
    
# "pathFile": "src/common/files/agentic-ai.txt"
# "pathFile": "src/common/files/schedule.json"
# "pathFile": "src/common/files/crew-contact.pdf"